# ABOUTME: Language-neutral path settings for shipping scripts
# ABOUTME: Read by both master_shipping.r and generate_signaldoc_browser.py

pathProject: /Users/Idrees/Desktop/CrossSection
pathStorage: /Users/Idrees/Desktop/CrossSection
OLD_PATH_RELEASES: https://drive.google.com/drive/folders/1EP6oEabyZRamveGNyzYU0u6qJ-N43Qfq
